url: https://dougie.io

paginate: 20
paginate_path: /:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title/
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post"

collections:
  notes:
    output: true
    permalink: /note/:categories/:title
  snippets:
    permalink: /s/:path
    output: true


include: [_redirects] # For Neflify
sass:
  sass_dir: _sass/

plugins: [jekyll-paginate]
