title: dougie.io
description: Business, Technology, and Practicality. Written by Doug Beney
url: https://dougie.io
author: Doug Beney

paginate: 20
paginate_path: /articles/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title/
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post"

collections:
  notes:
    output: true
    permalink: /note/:categories/:title
  snippets:
    permalink: /s/:path
    output: true

include: [_redirects] # For Netlify
sass:
  sass_dir: _sass/

plugins:
  - jekyll-paginate
  - jekyll-feed
